spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fish_board?useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
  session:
    store-type: none
  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 5MB

logging:
  level:
    org:
      hibernate: info
      springframework:
        web: debug
        security: debug

cloud:
  aws:
    s3:
      bucket: jini-fish-board
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

